SET SERVEROUTPUT ON;
CREATE TABLE CUST (ID NUMBER(10), NAME VARCHAR(10), ADDRESS VARCHAR(20) );
INSERT INTO CUST VALUES (1332,'SAHIL','PKL');
INSERT INTO CUST VALUES (1470,'MURTAZ','ZIRAKPUR');
INSERT INTO CUST VALUES (1409,'VATSAL','PKL');
DECLARE
	c_id cust.id%type := 8;
	c_name cust.name%type;
	c_addr cust.address%type;
BEGIN
	SELECT name, address into c_name, c_addr FROM cust WHERE id = c_id;
	DBMS_OUTPUT.PUT_LINE('NAME : '||c_name);
	DBMS_OUTPUT.PUT_LINE('ADDRESS : '||c_addr);
EXCEPTION
	WHEN no_data_found THEN
		DBMS_OUTPUT.PUT_LINE('NO CUSTOMERS !');
	WHEN others THEN
		DBMS_OUTPUT.PUT_LINE('ERRORS !');
END;